//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjektFinalny {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProjektFinalny.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualne notowanie waluty {0} to: {1} z dnia: {2}.
        /// </summary>
        internal static string ActualCurrencyRate {
            get {
                return ResourceManager.GetString("ActualCurrencyRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualnie obowiązujący kurs waluty - 1
        ///Ostatnie notowania dla waluty - 2.
        /// </summary>
        internal static string CurrencyOptions {
            get {
                return ResourceManager.GetString("CurrencyOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ile notowań waluty pobrać?.
        /// </summary>
        internal static string CurrencyRatesCount {
            get {
                return ResourceManager.GetString("CurrencyRatesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Podaj kod waluty.
        /// </summary>
        internal static string GetCurrencyCode {
            get {
                return ResourceManager.GetString("GetCurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualnie obowiązująca cena złota - 1
        ///Seria ostatnich wybranych notowań cen złota - 2
        ///Cena złota opublikowana w dniu dzisiejszym (albo brak danych) - 3
        ///Najwyższa cena złota z ostatnich 30 notowań - 4.
        /// </summary>
        internal static string GoldOptions {
            get {
                return ResourceManager.GetString("GoldOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ile notowań złota pobrać?.
        /// </summary>
        internal static string GoldRatesCount {
            get {
                return ResourceManager.GetString("GoldRatesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatnie notowania cen złota to:  {0}.
        /// </summary>
        internal static string LastCurrencyRates {
            get {
                return ResourceManager.GetString("LastCurrencyRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Ostatni dostępna cena złota to: {0} PLN z dnia {1}&quot;.
        /// </summary>
        internal static string LastGoldRateResult {
            get {
                return ResourceManager.GetString("LastGoldRateResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ostatnie notowania cen złota to:.
        /// </summary>
        internal static string LastGoldRates {
            get {
                return ResourceManager.GetString("LastGoldRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak notowań w dniu dzisiejszym.
        /// </summary>
        internal static string NoRatesToday {
            get {
                return ResourceManager.GetString("NoRatesToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brak waluty o kodzie: {0}.
        /// </summary>
        internal static string NoSuchCurrency {
            get {
                return ResourceManager.GetString("NoSuchCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dzisiejsza cena złota: {0}.
        /// </summary>
        internal static string TodayGoldRate {
            get {
                return ResourceManager.GetString("TodayGoldRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najwyższa cena złota z ostatnich 30 notowań to: {0} z dnia: {1}.
        /// </summary>
        internal static string TopGoldRate {
            get {
                return ResourceManager.GetString("TopGoldRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to W celu pobrania kursu walut wcisnij 1, zlota 2.
        /// </summary>
        internal static string WhatToDo {
            get {
                return ResourceManager.GetString("WhatToDo", resourceCulture);
            }
        }
    }
}
